AWSTemplateFormatVersion: "2010-09-09"
Description: Enable streaming Amazon Connect calls to Deepgram

Parameters:
  deepgramApiKey:
    Description: The Deepgram API key that will be used for transcription
    Type: String
  vpcId:
    Description: VPC where the ECS service will be deployed
    Type: AWS::EC2::VPC::Id
  subnets:
    Description: Subnets where the ECS service will be deployed
    Type: List<AWS::EC2::Subnet::Id>

Resources:
  kvsDgTrigger:
    Type: "AWS::Lambda::Function"
    Properties:
      Role: arn:aws:iam::764576996850:role/kvsDgTriggerRole
      Timeout: 30
      Environment:
        Variables:
          KVS_DG_INTEGRATOR_CLUSTER: !GetAtt kvsDgIntegratorEcsCluster.Arn
          KVS_DG_INTEGRATOR_TASK_DEFINITION: !Ref kvsDgIntegratorTaskDefinition
          KVS_DG_INTEGRATOR_SECURITY_GROUP: !Ref kvsDgIntegratorSecurityGroup
          KVS_DG_INTEGRATOR_SUBNETS: !Join [",", !Ref subnets]
          DEEPGRAM_API_KEY: !Ref deepgramApiKey
      PackageType: "Image"
      Code:
        ImageUri: 764576996850.dkr.ecr.us-east-1.amazonaws.com/kvs-dg-trigger:latest

  kvsDgIntegratorEcsCluster:
    Type: "AWS::ECS::Cluster"
    Properties:
      ClusterName: kvs-dg-integrator-cluster

  kvsDgIntegratorTaskDefinition:
    Type: "AWS::ECS::TaskDefinition"
    Properties:
      ContainerDefinitions:
        - Name: kvs-dg-integrator-container
          Image: 764576996850.dkr.ecr.us-east-1.amazonaws.com/kvs-dg-integrator:latest
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-stream-prefix: ecs
              awslogs-region: !Ref "AWS::Region"
              awslogs-group: kvs-dg-integrator
              awslogs-create-group: "true"
      Cpu: "256"
      ExecutionRoleArn: "arn:aws:iam::764576996850:role/kvsDgIntegratorRole"
      TaskRoleArn: "arn:aws:iam::764576996850:role/kvsDgIntegratorRole"
      Family: kvs-dg-integrator-task-family
      Memory: "512"
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      RuntimePlatform:
        OperatingSystemFamily: LINUX

  kvsDgIntegratorSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for kvs-dg-integrator Fargate task
      VpcId: !Ref vpcId
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          Description: Allow all outbound traffic
          IpProtocol: "-1"
