FROM gradle:8.3.0-jdk17 AS BUILD
COPY --chown=gradle:gradle . /home/gradle/src
WORKDIR /home/gradle/src
RUN gradle test --info --no-daemon
RUN gradle clean --no-daemon
RUN gradle shadowJar --no-daemon

FROM public.ecr.aws/lambda/java:17
COPY --from=BUILD /home/gradle/src/build/libs/*.jar ${LAMBDA_TASK_ROOT}/app.jar
RUN cd ${LAMBDA_TASK_ROOT} && jar -xf app.jar && rm app.jar
CMD [ "com.deepgram.kvsdgintegrator.KvsToDgStreamer::handleRequest" ]
